name: generate offline files & images

on:
  push:
    tags:
    - 'generate-v[0-9].[0-9]+.[0-9]+**'

jobs:
  generate-amd64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: generate files and images
        run: |
          bash v1.22.17/generate.sh
  generate-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: generate files and images
        run: |
          brew install ansible
          bash v1.22.17/generate.sh