name: buid images

on:
  push:
    branches:
    - main

jobs:
  prepare:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: generate files and images
        run: |
          bash prepare.sh
